### PR TITLE
bugfix -- not showing any counts

### PR DESCRIPTION
**Pull request by reinhrst**
I think this one is still open....

### CODE REVIEW

**Comment by DoomHammer** [comment]
Well, actually...

Take a look at #14 .

I think the current scope should be to make Glider **only** the representation layer of what's there in the SpaceAPI. SpaceAPI should in turn be fed by MQTT sensor readings (work in progress).

I made pialert2mqtt and thecount2mqtt projects, but ideally, The Count shuold talk to MQTT by itself.

**Comment by reinhrst** [comment]
OK. Should probably still have this bugfix though :)

**Comment by reinhrst** [comment]
Don't know how many dependencies are necessary to do MQTT, but shouldn't be too hard to add

**Comment by DoomHammer** [comment]
This bugfix is useful for the current code, but #14 removes its use, so these two are mutually exclusive (unless I'm mistaken).

And we don't need MQTT in the Glider itself. Again, Glider only asks the JSON endpoint, parses its content, and shows it to the Metaverse.

MQTT is served by the SpaceAPI server, like https://github.com/b4ckspace/spacestatus

**Comment by DoomHammer** [comment]
For now, we're relying on this: https://github.com/hs3city/pialert2spaceapi/blob/main/src/main.rs#L27

**Comment by DoomHammer** [comment]
Superseded by #14

**Pull request closed without merging**
